### ISSUE TITLE
Inquiry Regarding Scene Center Precomputation in MobileR2L Model Training

### ISSUE THREAD

**Issue by jingluoxixi** [snap-research/MobileR2L#11]
I'm currently working on training  MobileR2L model using a dataset that I captured. During this process, I've encountered an issue that I would like to seek your advice on.
In your colmap.py script, you precompute a scene center for the dataset. When training with my own dataset, the absence of this precomputed scene center has led to errors in the model training and resulted in inaccurate generated images. In the original NeRF, the scene center was not precomputed, and its values varied dynamically throughout the program execution.
Could you kindly explain the purpose of precomputing the scene center, and how these values are calculated? I am curious about the reasoning behind this requirement, and I'd like to understand how to implement this properly with my custom dataset.
Thank you very much for your time and for your contributions to this field. I look forward to your response.
![image](https://github.com/snap-research/MobileR2L/assets/168814371/be90fe05-64a5-4b18-b364-91907bb3516b)

**Comment by galalalala** [comment]
Hi, as written in the comment, the centers were calculated from the mean of the points in points3D.bin from the COLMAP. Note this is for forward-facing scenes(LLFF), the Blender scenes use camera centers instead. These centers will be used to recenter the camera poses as shown [here](https://github.com/snap-research/MobileR2L/blob/4f8929e8a1dcde14bd26565a2522e52c31c714f7/data/colmap.py#L273). Please reference the similar code in the NeRF paper [here](https://github.com/yenchenlin/nerf-pytorch/blob/63a5a630c9abd62b0f21c08703d0ac2ea7d4b9dd/load_llff.py#L140). The reason we use points center instead of camera center as the averge pose is because the teacher ngp_pl doesn't converge when centering the LLFF dataset with camera center as commented [here](https://github.com/snap-research/MobileR2L/blob/4f8929e8a1dcde14bd26565a2522e52c31c714f7/data/colmap.py#L159)
